Trait {
	#name : #TVBProgramNodeVisitor,
	#traits : 'TSmaCCParseNodeVisitor',
	#category : #'VBParser-Scanner'
}

{ #category : #generated }
TVBProgramNodeVisitor >> visitAddressOfClause: anAddressOfClause [
	^ self visitProgram: anAddressOfClause
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitArgument: anArgument [
	^ self visitProgram: anArgument
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitArgumentList: anArgumentList [
	^ self visitProgram: anArgumentList
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitArithmeticOperation: anArithmeticOperation [
	^ self visitProgram: anArithmeticOperation
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitAsType: anAsType [
	^ self visitProgram: anAsType
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitAsTypeAndNew: anAsTypeAndNew [
	^ self visitProgram: anAsTypeAndNew
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitAssignementOrEquals: anAssignementOrEquals [
	^ self visitProgram: anAssignementOrEquals
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitBaseType: aBaseType [
	^ self visitProgram: aBaseType
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitBlock: aBlock [
	^ self visitProgram: aBlock
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitBooleanLiteral: aBooleanLiteral [
	^ self visitProgram: aBooleanLiteral
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitCase: aCase [
	^ self visitProgram: aCase
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitColorLiteral: aColorLiteral [
	^ self visitProgram: aColorLiteral
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitComparisonOperation: aComparisonOperation [
	^ self visitProgram: aComparisonOperation
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitComplexType: aComplexType [
	^ self visitProgram: aComplexType
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitConcatenationOperation: aConcatenationOperation [
	^ self visitProgram: aConcatenationOperation
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitConfiguration: aConfiguration [
	^ self visitProgram: aConfiguration
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitConstant: aConstant [
	^ self visitProgram: aConstant
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitConstantList: aConstantList [
	^ self visitProgram: aConstantList
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitDateLiteral: aDateLiteral [
	^ self visitProgram: aDateLiteral
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitDefType: aDefType [
	^ self visitProgram: aDefType
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitDefineEnum: aDefineEnum [
	^ self visitProgram: aDefineEnum
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitDefineType: aDefineType [
	^ self visitProgram: aDefineType
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitDestinationList: aDestinationList [
	^ self visitProgram: aDestinationList
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitDictionaryAccess: aDictionaryAccess [
	^ self visitProgram: aDictionaryAccess
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitDimMultipleVariables: aDimMultipleVariables [
	^ self visitProgram: aDimMultipleVariables
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitDimVariable: aDimVariable [
	^ self visitProgram: aDimVariable
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitDoEvents: aDoEvents [
	^ self visitProgram: aDoEvents
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitDoUntilTrue: aDoUntilTrue [
	^ self visitProgram: aDoUntilTrue
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitDoWhileTrue: aDoWhileTrue [
	^ self visitProgram: aDoWhileTrue
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitElseIfBlock: anElseIfBlock [
	^ self visitProgram: anElseIfBlock
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitElseIfColon: anElseIfColon [
	^ self visitProgram: anElseIfColon
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitEnumEntry: anEnumEntry [
	^ self visitProgram: anEnumEntry
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitEquals: anEquals [
	^ self visitProgram: anEquals
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitError: anError [
	^ self visitProgram: anError
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitEvent: anEvent [
	^ self visitProgram: anEvent
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitExits: anExits [
	^ self visitProgram: anExits
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitExplicitAssignement: anExplicitAssignement [
	^ self visitProgram: anExplicitAssignement
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitExplicitCall: anExplicitCall [
	^ self visitProgram: anExplicitCall
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitExpressionList: anExpressionList [
	^ self visitProgram: anExpressionList
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitExternalFunction: anExternalFunction [
	^ self visitProgram: anExternalFunction
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitExternalSub: anExternalSub [
	^ self visitProgram: anExternalSub
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitFileDescriptorLiteral: aFileDescriptorLiteral [
	^ self visitProgram: aFileDescriptorLiteral
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitFloatLiteral: aFloatLiteral [
	^ self visitProgram: aFloatLiteral
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitForEach: aForEach [
	^ self visitProgram: aForEach
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitForNext: aForNext [
	^ self visitProgram: aForNext
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitForStepNext: aForStepNext [
	^ self visitProgram: aForStepNext
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitFunctionDefinition: aFunctionDefinition [
	^ self visitProgram: aFunctionDefinition
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitGoSub: aGoSub [
	^ self visitProgram: aGoSub
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitGoSubLabel: aGoSubLabel [
	^ self visitProgram: aGoSubLabel
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitGoToStatement: aGoToStatement [
	^ self visitProgram: aGoToStatement
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitGuidLiteral: aGuidLiteral [
	^ self visitProgram: aGuidLiteral
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitHashIdentifier: aHashIdentifier [
	^ self visitProgram: aHashIdentifier
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitHeader: aHeader [
	^ self visitProgram: aHeader
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitHeadlessDictionaryAccess: aHeadlessDictionaryAccess [
	^ self visitProgram: aHeadlessDictionaryAccess
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitHeadlessIdentifier: aHeadlessIdentifier [
	^ self visitProgram: aHeadlessIdentifier
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitIfThenColon: anIfThenColon [
	^ self visitProgram: anIfThenColon
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitIfThenElse: anIfThenElse [
	^ self visitProgram: anIfThenElse
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitIfThenElseIfElse: anIfThenElseIfElse [
	^ self visitProgram: anIfThenElseIfElse
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitImplements: anImplements [
	^ self visitProgram: anImplements
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitImplicitParenthesesLessCall: anImplicitParenthesesLessCall [
	^ self visitProgram: anImplicitParenthesesLessCall
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitInfinityLoop: anInfinityLoop [
	^ self visitProgram: anInfinityLoop
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitIntegerLiteral: anIntegerLiteral [
	^ self visitProgram: anIntegerLiteral
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitInterval: anInterval [
	^ self visitProgram: anInterval
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitIntervalExpression: anIntervalExpression [
	^ self visitProgram: anIntervalExpression
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitLabel: aLabel [
	^ self visitProgram: aLabel
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitLabelTag: aLabelTag [
	^ self visitProgram: aLabelTag
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitLen: aLen [
	^ self visitProgram: aLen
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitLineInputClause: aLineInputClause [
	^ self visitProgram: aLineInputClause
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitMemberAccess: aMemberAccess [
	^ self visitProgram: aMemberAccess
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitModule: aModule [
	^ self visitProgram: aModule
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitModuleAttribute: aModuleAttribute [
	^ self visitProgram: aModuleAttribute
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitModuleConstant: aModuleConstant [
	^ self visitProgram: aModuleConstant
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitModuleMultipleConstants: aModuleMultipleConstants [
	^ self visitProgram: aModuleMultipleConstants
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitModuleMultipleProperties: aModuleMultipleProperties [
	^ self visitProgram: aModuleMultipleProperties
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitModuleProperty: aModuleProperty [
	^ self visitProgram: aModuleProperty
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitModulePropertyGet: aModulePropertyGet [
	^ self visitProgram: aModulePropertyGet
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitNegatedOperation: aNegatedOperation [
	^ self visitProgram: aNegatedOperation
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitNewClause: aNewClause [
	^ self visitProgram: aNewClause
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitNotOperation: aNotOperation [
	^ self visitProgram: aNotOperation
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitNull: aNull [
	^ self visitProgram: aNull
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitOnErrorGoTo: anOnErrorGoTo [
	^ self visitProgram: anOnErrorGoTo
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitOnErrorResumeNext: anOnErrorResumeNext [
	^ self visitProgram: anOnErrorResumeNext
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitOnExpressionGo: anOnExpressionGo [
	^ self visitProgram: anOnExpressionGo
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitOpenClause: anOpenClause [
	^ self visitProgram: anOpenClause
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitOptionBase: anOptionBase [
	^ self visitProgram: anOptionBase
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitOptionCompare: anOptionCompare [
	^ self visitProgram: anOptionCompare
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitOptionCompareDatabase: anOptionCompareDatabase [
	^ self visitProgram: anOptionCompareDatabase
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitOptionExplicit: anOptionExplicit [
	^ self visitProgram: anOptionExplicit
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitOptionPrivateModule: anOptionPrivateModule [
	^ self visitProgram: anOptionPrivateModule
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitOptionValue: anOptionValue [
	^ self visitProgram: anOptionValue
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitParameter: aParameter [
	^ self visitProgram: aParameter
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitParameterList: aParameterList [
	^ self visitProgram: aParameterList
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitParameterPassingStrategy: aParameterPassingStrategy [
	^ self visitProgram: aParameterPassingStrategy
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitParentheseesExpression: aParentheseesExpression [
	^ self visitProgram: aParentheseesExpression
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitParentheseesValueStatement: aParentheseesValueStatement [
	^ self visitProgram: aParentheseesValueStatement
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitPositiveOperation: aPositiveOperation [
	^ self visitProgram: aPositiveOperation
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitPrintIntoFileClause: aPrintIntoFileClause [
	^ self visitProgram: aPrintIntoFileClause
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitProcedureCallOrArrayAccess: aProcedureCallOrArrayAccess [
	^ self visitProgram: aProcedureCallOrArrayAccess
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitProgram: aProgram [
	^ self visitSmaCCParseNode: aProgram
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitQualifiedIdentifier: aQualifiedIdentifier [
	^ self visitProgram: aQualifiedIdentifier
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitRaiseError: aRaiseError [
	^ self visitProgram: aRaiseError
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitRaiseEvent: aRaiseEvent [
	^ self visitProgram: aRaiseEvent
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitReDimMultipleVariables: aReDimMultipleVariables [
	^ self visitProgram: aReDimMultipleVariables
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitReDimVariable: aReDimVariable [
	^ self visitProgram: aReDimVariable
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitRename: aRename [
	^ self visitProgram: aRename
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitResumeEmpty: aResumeEmpty [
	^ self visitProgram: aResumeEmpty
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitResumeLabel: aResumeLabel [
	^ self visitProgram: aResumeLabel
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitResumeNext: aResumeNext [
	^ self visitProgram: aResumeNext
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitReturn: aReturn [
	^ self visitProgram: aReturn
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitSelect: aSelect [
	^ self visitProgram: aSelect
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitSetUpAssignation: aSetUpAssignation [
	^ self visitProgram: aSetUpAssignation
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitSimpleIdentifier: aSimpleIdentifier [
	^ self visitProgram: aSimpleIdentifier
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitSquareBracketIdentifier: aSquareBracketIdentifier [
	^ self visitProgram: aSquareBracketIdentifier
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitStaticMultipleVariables: aStaticMultipleVariables [
	^ self visitProgram: aStaticMultipleVariables
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitStaticVariable: aStaticVariable [
	^ self visitProgram: aStaticVariable
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitStringLiteral: aStringLiteral [
	^ self visitProgram: aStringLiteral
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitSubDefinition: aSubDefinition [
	^ self visitProgram: aSubDefinition
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitTypeEntry: aTypeEntry [
	^ self visitProgram: aTypeEntry
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitTypeOf: aTypeOf [
	^ self visitProgram: aTypeOf
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitTypeSize: aTypeSize [
	^ self visitProgram: aTypeSize
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitTypedThing: aTypedThing [
	^ self visitProgram: aTypedThing
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitUntilTrue: anUntilTrue [
	^ self visitProgram: anUntilTrue
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitValueStatementList: aValueStatementList [
	^ self visitProgram: aValueStatementList
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitVariable: aVariable [
	^ self visitProgram: aVariable
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitVariableList: aVariableList [
	^ self visitProgram: aVariableList
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitWhileTrue: aWhileTrue [
	^ self visitProgram: aWhileTrue
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitWhileWend: aWhileWend [
	^ self visitProgram: aWhileWend
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitWith: aWith [
	^ self visitProgram: aWith
]

{ #category : #generated }
TVBProgramNodeVisitor >> visitWithMemberAccess: aWithMemberAccess [
	^ self visitProgram: aWithMemberAccess
]
